components/users/forms.py
# Form Based Imports
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired,Email,EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

# User Based Imports
from flask_login import current_user
from components.models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

    def validate_email(self, field):
        # attempt to get the user
        user = User.query.filter_by(email=field.data).first()
        # if this email does not exist
        if user is None:
            raise ValidationError('this email is not registered')




class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    name = StringField('Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords Must Match!')])
    pass_confirm = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register!')


    def validate_email(self, field):
        # Check if not None for that user email!
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def validate_username(self, field):
        # Check if not None for that username!
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Sorry, that username is taken!')

class UpdateUserForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(),Email(message="Must be an email")])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png','jpeg','bmp','bmp','gif','webp'],message="This file type is not allowed")])
    submit = SubmitField('Update')
    bio = TextAreaField('Bio')

components/users/__init__.py
# adding this file to treat the users folder
# as a module

components/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required ,login_required
from components import db
from werkzeug.security import generate_password_hash,check_password_hash
from components.models import User, Post
from components.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from components.users.picture_handler import add_profile_pic, add_post_pic
from components.posts.forms import WritePost

# setting the users blueprint
users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(email=form.email.data,
                    username=form.username.data,
                    name = form.name.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash("Account created. Please log in to continue")
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table

        user = User.query.filter_by(email=form.email.data).first()



        if user.check_password(form.password.data):
            #Log in the user

            login_user(user)



            next = request.args.get('next')


            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
        else:
            form.password.errors.append('incorrect password')
    return render_template('login.html', form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    account_form = UpdateUserForm()
    post_form = WritePost()
    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    posts = current_user.posts

    # checking the account form
    if account_form.validate_on_submit():
        if account_form.picture.data:
            username = current_user.username
            pic = add_profile_pic(account_form.picture.data,username)
            current_user.profile_image = pic


        # checking that other users don't have the requested email or username

        #if username already exist and not current user explain username is taken
        searched_user = User.query.filter_by(username=account_form.username.data).first()
        if searched_user and not searched_user.username==current_user.username:
            account_form.username.errors.append(account_form.username.data +' is already taken')
            user_update_failed = True
            return render_template('user.html', profile_image=profile_image, account_form=account_form,post_form=post_form, user=current_user, posts=posts ,user_update_failed=user_update_failed )

        #if email already exist and not current user explain email is taken
        searched_user = User.query.filter_by(email=account_form.email.data).first()
        if searched_user and not searched_user.email==current_user.email:
            user_update_failed = True
            account_form.email.errors.append('email is already registered')
            profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
            return render_template('user.html', profile_image=profile_image, account_form=account_form,post_form=post_form, user=current_user, posts=posts, user_update_failed=user_update_failed)


        current_user.username = account_form.username.data
        current_user.email = account_form.email.data
        current_user.bio = account_form.bio.data

        db.session.commit()

        return redirect(url_for('users.account'))


    # Cheking the post form
    if post_form.validate_on_submit():

        text = post_form.text.data
        post = Post(user_id=current_user.id, text=text)
        db.session.add(post)
        db.session.commit()

        if post_form.picture.data:
            pic = add_post_pic(post_form.picture.data,post.id)
            post.image = pic
            db.session.add(post)
            db.session.commit()


        return redirect(url_for('users.account'))


    return render_template('user.html', profile_image=profile_image, account_form=account_form,post_form=post_form, user=current_user, posts=posts )


@users.route("/user/<username>",methods=['GET', 'POST'])
@login_required
def u(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return render_template('error_pages/404.html'), 404
    else:
        # this means the user exists

        account_form = UpdateUserForm()
        post_form = WritePost()
        profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
        posts = user.posts

        # checking the account form
        if account_form.validate_on_submit():
            if account_form.picture.data:
                username = current_user.username
                pic = add_profile_pic(account_form.picture.data,username)
                current_user.profile_image = pic


            # checking that other users don't have the requested email or username

            #if username already exist and not current user explain username is taken
            searched_user = User.query.filter_by(username=account_form.username.data).first()
            if searched_user and not searched_user.username==current_user.username:
                flash("This username is already taken")
                return redirect(url_for('users.account'))

            #if email already exist and not current user explain email is taken
            searched_user = User.query.filter_by(email=account_form.email.data).first()
            if searched_user and not searched_user.email==current_user.email:
                flash("This email is already taken")
                profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
                return redirect(url_for('users.account'))


            current_user.username = account_form.username.data
            current_user.email = account_form.email.data
            current_user.bio = account_form.bio.data

            db.session.commit()

            return redirect(url_for('users.u',username=username))


        # Cheking the post form
        if post_form.validate_on_submit():

            text = post_form.text.data
            post = Post(user_id=current_user.id, text=text)
            db.session.add(post)
            db.session.commit()

            if post_form.picture.data:
                pic = add_post_pic(post_form.picture.data,post.id)
                post.image = pic
                db.session.add(post)
                db.session.commit()


            return redirect(url_for('users.u',username=username))


        return render_template('user.html', profile_image=profile_image, account_form=account_form,post_form=post_form, user=user, posts=posts )

components/templates/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/grayshift.min.css'  )}}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap">
</head>
<body>
  <nav class="navbar-default sticky-top bg-card shadow">
    <div class="container d-flex align-items-center">
      <a class="link-headings d-none d-lg-inline pt-4" href="{{ url_for('core.index') }}">
        <h1 class="gi gi-fellowers mb-5 fs-4" width="111.66" height="40">Twitter Clone</h1>
      </a>
      <ul class="list-unstyled d-flex flex-grow-1 justify-content-between flex-lg-grow-0 mx-lg-auto">
        <li class="nav-item">
          <a class="nav-link active py-3 px-lg-5 py-lg-4 text-light" href="{{ url_for('core.index') }}">
            <svg class="gi gi-home fs-5" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M2.336 11.253l-.08.08C1.685 11.956 2.12 13 3 13h1.116l.892 7.124A1 1 0 0 0 6 21h4a1 1 0 0 0 1-1v-4.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5V20a1 1 0 0 0 1 1h4l.115-.007a1 1 0 0 0 .877-.869l.89-7.124H21c.92 0 1.352-1.137.664-1.747l-9-8a1 1 0 0 0-1.329 0l-9 8z"/>
            </svg>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link  py-3 px-lg-5 py-lg-4" href="{{ url_for('users.account') }}" aria-current="page">
            <svg class="gi gi-users fs-5" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M9 13c1.93 0 3.677.78 4.943 2.043C14.787 14.4 15.848 14 17 14a5 5 0 0 1 5 5 1 1 0 0 1-1 1h-5a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1 7 7 0 0 1 7-7zM9 3a4 4 0 1 1 0 8 4 4 0 1 1 0-8zm8 10a3 3 0 1 0 0-6 3 3 0 1 0 0 6z"/>
            </svg>
          </a>
        </li>

      </ul>
      <form>
        <div class="input-group d-none d-lg-flex mr-3">
          <div class="input-group-item">
            <svg class="gi gi-search fs-3" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M11 3a8 8 0 0 1 8 8c0 1.848-.627 3.55-1.68 4.905l3.386 3.388a1 1 0 0 1-1.32 1.497l-.094-.083-3.388-3.386C14.55 18.373 12.848 19 11 19a8 8 0 1 1 0-16zm0 2a6 6 0 1 0 0 12 6 6 0 1 0 0-12z"/>
            </svg>
          </div>
          <input class="form-control disabled" style="max-width: 9rem;" type="search" placeholder="Search" aria-label="Search" >
        </div>
      </form>
      <!-- profile image with drop down -->
      <div class="dropdown">
        <button class="btn p-0" data-toggle="dropdown" type="button" aria-expanded="false">
          <span class="visually-hidden">Toggle Dropdown</span>
          <img class="gi d-none d-lg-inline-block rounded-circle" height="48" width="48" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{{ url_for('users.account') }}">Account</a>
          <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </nav>
<br><br><br>
  <!-- end of navbar -->
  <div class="container">

    <div class="row justify-content-center">

      <div class="col-lg-12 col-xl-6">


      <!-- fake write a post part --->
      <!-- when clicked it will show the full write a post -->
      <div class="card py-0 mb-5" data-toggle="modal" data-target="#newPost">
        <div class=" row pl-4 pt-4">
            <div class="col-auto p-0 m-0">
              <svg class="gi gi-edit-2 mr-3 fs-3 text-primary" width="1.3em" height="1.3em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>                  </svg>
            </div>
            <div class="col-auto p-0 m-0">
                <span class="text-muted">Write a post</span>
              </div>



        </div>

        <hr class="p-0 m-0 mt-1 ">
        <div class="row align-items-center ">
            <div class="col-sm-8 col-md-9">

            </div>
        </div>
        <div class="py-3">

          <form>
                    <div class="row align-items-center">
                      <div class="col-sm-8 col-md-9">
                        <div class="input-group mb-5 mb-sm-0">
                          <div class="input-group-item pr-5 pl-0 bg-transparent">
                            <img class="gi rounded-circle" height="48" width="48" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
                          </div>
                          <input class="form-control p-0 bg-transparent" type="text" placeholder="What's on your mind?" aria-label="What's on your mind?">
                        </div>
                      </div>
                      <div class="col-sm-4 col-md-3">
                        <button class="btn btn-primary w-100" type="submit">Post</button>
                      </div>
                    </div>
                  </form>


        </div>
      </div>
        <!-- write a post pop up end -->

        {% for post in posts %}

        <!-- post  -->
        <div class="card mb-5 mb-lg-0">
          <div class="d-flex mb-5">
            <img class="gi mr-3 rounded-circle" width="48" height="48" src="{{ url_for('static', filename='profile_pics/' + post.user.profile_image) }}">
            <div class="mr-auto overflow-hidden">
              <div class="d-flex">
                <h4 class="text-truncate mr-2 fs-1 lh-relaxed">
                  <a class="link-headings" href="{{ url_for('users.u', username=post.user.username) }}">{{ post.user.name }}</a>
                </h4>
                <span class="mr-2">&middot;</span>
                <!-- CHANGE THIS TO TIME THAT HAS PASSED -->
                <p>{{post.date.strftime('%Y-%m-%d')}}</p>
              </div>
              <p class="text-truncate">@{{ post.user.username }}</p>
            </div>
            <div class="dropdown ml-5">
              <button class="btn btn-auto d-inline-flex flex-shrink-0 align-items-center justify-content-center p-0 rounded-circle" data-toggle="dropdown" style="width: 1.5rem; height: 1.5rem;" type="button" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
                <svg class="gi gi-more-horizontal" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5 14a2 2 0 1 0 0-4 2 2 0 1 0 0 4zm7 0a2 2 0 1 0 0-4 2 2 0 1 0 0 4zm7 0a2 2 0 1 0 0-4 2 2 0 1 0 0 4z"/>
                </svg>
              </button>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Action</a>
              </div>
            </div>
          </div>
          <p class="mb-5">{{post.text}}</p>
          <div class="position-relative">
            {% if post.image is not none %}
                <center><img class="gi gi-reply rounded justify-centered w-100 " src="{{ url_for('static', filename='post_pics/' + post.image) }}" ></center>
            {% endif %}



          </div>
          <hr role="presentation">
          <div class="row invisible-scrollbar flex-nowrap">
            <div class="col">
              <div class="d-flex">
                <button class="btn link-body d-inline-flex p-0 mr-3" type="button">
                  <svg class="gi gi-heart fs-3" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M3.555 5a5.31 5.31 0 0 1 7.506 0l.938.938.94-.938a5.31 5.31 0 0 1 7.506 0 5.31 5.31 0 0 1 0 7.506l-7.737 7.737a1 1 0 0 1-1.414 0l-7.737-7.737a5.31 5.31 0 0 1 0-7.506z"/>
                  </svg>
                </button>
                <!-- number of likes goes here once this is added -->
                <p></p>
              </div>
            </div>
            <div class="col">
              <div class="d-flex">
                <button class="btn link-body d-inline-flex p-0 mr-3" data-toggle="collapse" data-target="#collapseTwo" type="button" aria-expanded="false" aria-controls="collapseTwo">
                  <svg class="gi gi-message-circle fs-3" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.397 2.124c3.23-.5 6.4.52 8.674 2.804s3.307 5.446 2.804 8.674c-.636 4.077-3.92 7.457-7.987 8.22-1.957.366-3.95.156-5.765-.61-.16-.066-.398-.135-.644-.088h0l-4.283.856a.93.93 0 0 1-.196.02 1 1 0 0 1-.98-1.196h0l.857-4.288c.04-.193.01-.41-.09-.64-.767-1.813-.978-3.807-.61-5.765.763-4.067 4.143-7.35 8.22-7.987zM8 11a1 1 0 1 0 0 2 1 1 0 1 0 0-2zm4 0a1 1 0 1 0 0 2 1 1 0 1 0 0-2zm4 0a1 1 0 1 0 0 2 1 1 0 1 0 0-2z"/>
                  </svg>
                </button>
                <!-- number of comments is added here once this is added -->
                <p></p>
              </div>
            </div>

          <div class="col"></div>
          <div class="col"></div>
          </div>
        </div>
        <!-- end of post -->

 <br><br><br>
          {% endfor %}
      </div>
    </div>
  </div>
  </div>

  <!-- Write a Post Popup -->
  <div class="modal fade" id="newPost" tabindex="-1" aria-labelledby="newPost" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header shadow-none pb-1">

        <h2 class="fs-2" id="settingsModalLabel">Write a Post...</h2>
        <button class="btn btn-auto d-inline-flex flex-shrink-0 align-items-center justify-content-center p-0 rounded-circle" data-dismiss="modal" style="width: 2.5rem; height: 2.5rem;" type="button" aria-label="Close">
          <svg class="gi gi-x fs-3" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M7.613 6.2l.094.083L12 10.585l4.293-4.292.094-.083a1 1 0 0 1 1.403 1.403l-.083.094L13.415 12l4.292 4.293a1 1 0 0 1-1.32 1.497l-.094-.083L12 13.415l-4.293 4.292-.094.083a1 1 0 0 1-1.403-1.403l.083-.094L10.585 12 6.293 7.707a1 1 0 0 1 1.32-1.497z"/>
          </svg>
        </button>
      </div>
      <div class="modal-body rounded-bottom">
        <div class="tab-content">
          <div class="tab-pane fade show active" id="settingsAccount" role="tabpanel">
            <!-- a form for making a post -->
            <form  method="POST" enctype="multipart/form-data">
               {{ post_form.hidden_tag() }}
               {% for error in post_form.text.errors %}
               <i><span class="text-danger  pt-0 ml-3 mb-0 pb-0 fw-light" style="font-size:13px"> {{error}} </span></i>
               {% endfor %}
               {{ post_form.text(class="form-control form-control-lg mb-5",  rows="3", placeholder="Express yourself") }}

               {{ post_form.picture.label(class="form-label") }}
               {{ post_form.picture(class="form-control form-control-lg mb-5") }}

               {{ post_form.submit(class="btn btn-lg btn-primary w-100") }}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  <!-- write a post pop up end -->

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-t6I8D5dJmMXjCsRLhSzCltuhNZg6P10kE0m0nAncLUjH6GeYLhRU1zfLoW3QNQDF" crossorigin="anonymous"></script>
  </body>
  </html>

components/templates/login.html
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Sign in</title>
      <link rel="stylesheet" href="{{ url_for('static', filename='assets/grayshift.min.css'  )}}">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap">
   </head>
   <body>
      <div class="d-flex align-items-center min-vh-100 py-6 mx-auto" style="max-width: 404px;">
         <div class="container">
            <div class="text-center mb-6">
               <a class="link-headings" href="#">
                  <h1 class="mb-5 fs-4">Twitter Clone</h1>
               </a>
            </div>
            <div class="card mb-5">
               <form method="POST">
                 {{ form.hidden_tag() }}
                  <center>
                     <h1 class="mb-2 fs-3">Sign in</h1>
                     {% with messages = get_flashed_messages() %}
                     {% if messages %}
                     {% for message in messages %}
                        <i> <span class="text-success mt-0 pt-0  fw-light" style="font-size:13px"> {{message}} </span></i>
                    {% endfor %} {% endif %}
                    {% endwith %}
                    <div class="mb-3">
                  </center>
                  {% for error in form.email.errors %}
                        <i><span class="text-danger mt-0 pt-0 ml-3 fw-light" style="font-size:13px">{{error}}</span></i>
                    {% endfor %}
                  <div class="input-group mb-0">
                    <!-- email svg -->
                     <div class="input-group-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                           <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                        </svg>
                     </div>
                     <!-- the email inout -->
                     {{ form.email(class="form-control form-control-lg", **{'placeholder':"Email", 'required':'true', 'autofocus':'true'}) }}



                  </div>
                  <div class="mb-5"></div>

                  {% for error in form.password.errors %}
                        <i><span class="text-danger mt-0 pt-0 ml-3 fw-light" style="font-size:13px">{{error}}</span></i>
                    {% endfor %}
                  <div class="input-group mb-5">
                    <!-- the lock svg -->
                     <div class="input-group-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                           <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                        </svg>
                     </div>
                     {{ form.password(class="form-control form-control-lg", **{'type':'password', 'placeholder':"Password", 'aria_label':"Password", 'required':true}) }}
                  </div>

                    <div class="mb-5"></div>
                  <center><span data-toggle="tooltip" data-placement="right" title="Not implemented yet"><a href="#" >Forgot password?</a></span></center>
                  {{ form.submit(class="btn btn-lg btn-primary w-100 mt-3") }}
               </form>
            </div>
            <div class="card">
               <p class="text-center">Don't have an account? <a href="{{ url_for('users.register') }}">Sign up</a>.</p>
            </div>
         </div>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-t6I8D5dJmMXjCsRLhSzCltuhNZg6P10kE0m0nAncLUjH6GeYLhRU1zfLoW3QNQDF" crossorigin="anonymous"></script>
   </body>
</html>